### PR TITLE
Add installation of phalcon to scrutinizer

### PR DESCRIPTION
**Pull request by harikt**
Hi , 

Let us test this. I believe this should work.

Let us see how things work.

Thank you

### CODE REVIEW

**Comment by harikt** [comment]
Hi, 

Do you have any idea how to fix the 404 not found ? https://scrutinizer-ci.com/g/tmquang6805/phalex/inspections/6fc327b1-5e1f-46ef-a987-0b38c78694e5

Seems like the package is broken. Does this helps some what ? or you were in trouble here ?

**Comment by tmquang6805** [comment]
@harikt 
It seem not work. 
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20121212/phalcon.so' - /usr/lib/php5/20121212/phalcon.so: undefined symbol: compiler_globals in Unknown on line 0
```
https://scrutinizer-ci.com/g/tmquang6805/phalex/inspections/8d64ef35-0848-4ef3-b1da-8ee147bbad86/log

**Comment by harikt** [comment]
@tmquang6805 I have seen it. Was asking the same to @scrutinizer-ci team.

**Comment by tmquang6805** [comment]
@harikt Thanks you :smile:

**Pull request merged**
